---
title: "Simulating Pedigrees"
author: Joel Pick
output: 
  pdf_document
---
I think a nice approach for the core simulation is to have parameters that are things that can be estimated from a given pedigree (with columns of id, dam, sire and cohort). The nice things about this is that we can take a given pedigree, extract these parameters, simulate a bunch pedigrees from the parameters and then compare them back other metrics (number of half-sibs, parent-offspring links etc), which will allow us to evaluate the simulations in some way.

## Current Assumptions
I think there is potential for these to change in future versions, but for now are fixed

- Random mating
- Equal sex ratio
- No selection
- No non-stochastic (e.g. between individual) variation in survival or fecundity
- Constant survival and fecundity (i.e. no age- or sex-specific vital rates, no senescence etc)

## Basic parameters
These basically describe how big the simulation is going to be

- Number of years
- Starting number of females
    
## Vital rates (implemented)
Broadly these relate to the Leslie matrix, and are generally parameters associated with females

- **Fecundity**: number of offspring (zygotes) per female
    - Do we want this to vary, and if so how. Poisson? Annual fecundity is often very under-dispersed. Conway-Maxwell Poisson is perhaps a good option
- **Juvenile survival**: probability of survival from recording point until (local) recruitment
- **Adult survival**: probability of survival from one breeding season to the next
- **Immigration**: proportion immigrants each year
    - easy to implement, hard to measure from a pedigree
- **Constant population size?** Whether a constant number of individuals survive each year or whether population size is allowed to stochastically fluctuate

### Extra vital rates like parameters to consider

- **Probability of breeding** (not possible to disentangled from detection probability in a year in a given pedigree)
- **Age at first reproduction** Possibly as modal age?
- These two could be combined as an age specific probability of breeding


## Mating system (not implemented)
I think we can describe the mating system with 3-4 parameters. The way I have thought about this is to assign each female a 'social' male. There are then 

- **Within-year polyandry**: Probability that 'social male' sires offspring, or a random male 
    - This is essentially probability of EPP within a females offspring. If the concept of social male doesn't exist for a species, then the probability can be 0. If no EPP, then it can be 1.
- **Between-year polyandry**: Probability of retaining the same 'social male' between years (if alive). 
    - If social males don't exist, then setting Within-year polyandry above as 0, will make this parameter redundant
- **Polygyny rate** / male reproductive skew
    - I think this is the most complex part. I was thinking of something like there being a beta distribution of probabilities that a male sires a brood, then social males are sampled with those probabilities. Extra pair paternity are also sampled from those same probabilities.
    - There would be a new beta distribution every year. So some males would be 'good' in one year and 'bad' in another. However, the between-year polyandry above would essentially act to transfer male 'dominance' across years.

